### PR TITLE
Add svg files of oemof logo

### PR DESCRIPTION
**Pull request by fwitte**
I tried to find the logos as vector graphics, but was not able to find the correct logo (only a twisted version). I recreated the logo as svg image and put it into the larger banners, too. Feedback is appreciated :)!

### CODE REVIEW

**Comment by fwitte** [comment]
Interestingly, the logos look different on my PC.

**Comment by fwitte** [comment]
The issue seems to be, that the browser is not able to render the font (see [here](https://graphicdesign.stackexchange.com/questions/77241/svg-image-looks-odd-in-html-page)).

> Your font was replaced.
> 
> Compare each character and you will see some slight differences. The browser is responsible for rendering an SVG file. If it doesn't have access to a font, or if it doesn't understand the font specification, it'll revert to a fallback.
> 
> The solution is to convert the text to paths with Ctrl + Shift + C. This will make your text un-editable, but it will be rendered correctly.
> 
> As a general rule, I always convert text to paths in SVG files intended for the web. I typically use layers, so that one layer has the editable text. I then duplicate it, hide the original, and do the conversion. This way, I can edit the text again if I need to.

I will export the font to a path, so the browser renders the logo as wished.

**Comment by jnnr** [comment]
Looks good :)

**Comment by uvchik** [comment]
Would be nice to have an editable version with the original fonts. Thanks for your contribution! :tada:

**Comment by fwitte** [comment]
> Would be nice to have an editable version with the original fonts. Thanks for the enhancement! :tada: 

Will add that version.

**Pull request merged**
